### PR TITLE
Convert HTML entities in Slack notifications

### PR DESCRIPTION
**Pull request by christ0ph3r**
This issue was mentioned here
https://github.com/gedex/wp-slack/issues/27

- christ0ph3r

### CODE REVIEW

**Comment by michael-cannon** [comment]
@christ0ph3r The code needs WP coding standards check for spacing around parenthesis. Noted in code #e6da26b

**Comment by christ0ph3r** [comment]
Thanks @michael-cannon

**Comment by christ0ph3r** [comment]
Thanks for pointing that out @natebot . It didn't work for me without 'UTF-8'.  Do you know what I would have to put in my php.ini file?  

Do you think it could benefit others who may not have that setting configured or may be not able to access that file?

**Comment by christ0ph3r** [comment]
Hey @natebot 

A lot of people running WordPress are using PHP 5.3 still.  

Reference: https://wordpress.org/about/stats/

I think it would be best to leave backwards compatibility to people running older versions.

I am unsure about the constant.   Maybe @gedex knows.

**Comment by gedex** [comment]
@christ0ph3r @natebot I've merged this into `master` and will release the changes in `0.6.0`. The third argument, encoding, for `html_entity_decode` is highly encouraged, so I set it to `get_bloginfo( 'charset' )` -- will default to `UTF-8` if unset.

Thank you for working on this, I really appreciate this.

**Comment by beaurushton** [comment]
Is there ever going to be a 0.6.0 release with this fix included?

**Pull request closed without merging**
